### ISSUE TITLE
Sign in experience has been deprecated

### ISSUE THREAD

**Issue by clovis1122** [Lzok/remix-auth-linkedin#1]
From what I read at https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin, it seems the current sign in implementation was deprecated and no longer works for new applications. Instead, they need to be configured using openid connect: https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2.

**Comment by natac13** [comment]
I have a [PR open](https://github.com/Lzok/remix-auth-linkedin/pull/2) to address this if you want to give it a try.

**Comment by Lzok** [comment]
@clovis1122 Thank you for bringing the issue/update here. 
@natac13 Thank you for the PR! Very appreciated.

Let's continue the conversation in the PR.

**Comment by Lzok** [comment]
@clovis1122 @natac13 I'm sorry for the delay. I just commented on the PR.
